#!/bin/sh
HORUSSRV_HOME=/home/lmarcio/101-UFRJ/999-Tese_Doutorado-Projeto_Horus-Luiz_Marcio_Faria_Aquino_Viana/HORUSSRV_v2.0/

CFGFILE=./server_conf.cfg

SRCDIR=$HORUSSRV_HOME/Appl/Servidor/HORUSSRV
EXEFILE=$SRCDIR/horussrv
LOGFILE=$SRCDIR/horussrv-$(date +%Y%m%d_%H%M%S).log

# SAMPLE DATABASE REBUILD
#HORUS_OPTS=-r

# START DATABASE WITH TEST LISTENER
#HORUS_OPTS=-tl

# START DATABASE WITH LISTENER
#HORUS_OPTS=-l

# START DATABASE WITH LISTENER AND EXECUTE BENCHMARK
HORUS_OPTS=-e

cd $SRCDIR
#$EXEFILE $CFGFILE $HORUS_OPTS > $LOGFILE
$EXEFILE $CFGFILE $HORUS_OPTS
cd $SRCDIR

