#!/bin/sh
HORUSSRV_HOME=/home/lmarcio/101-UFRJ/999-Tese_Doutorado-Projeto_Horus-Luiz_Marcio_Faria_Aquino_Viana/HORUSSRV_v2.0/
export HORUSSRV_HOME

CFGFILE=./server_conf.cfg

SRCDIR=$HORUSSRV_HOME/Appl/Servidor/HORUSSRV
BINDIR=$HORUSSRV_HOME/Appl/Servidor/HORUSSRV
DATADIR=$HORUSSRV_HOME/Data
EXEFILE=$BINDIR/horussrv
LOGFILE=$BINDIR/horussrv-$(date +%Y%m%d_%H%M%S).log

cd $SRCDIR

make clean
make all

#cp -aux $SRCDIR/horussrv $BINDIR/

# SAMPLE DATABASE DELETE
rm -f $DATADIR/*dat
rm -f $DATADIR/HORUSSRV11/*hdi
rm -f $DATADIR/HORUSSRV11/*dat
rm -f $DATADIR/HORUSSRV11/HORUSSRV11_DAT/*dat
rm -f $DATADIR/HORUSSRV11/HORUSSRV11_DAT/tbl_imgrio_temp/*

HORUS_CMDLINE_REBUILD=-r
#HORUS_CMDLINE_REMOTEEXEC=-rb
HORUS_CMDLINE_REMOTEEXEC=-r2

cd $BINDIR

$EXEFILE $CFGFILE $HORUS_CMDLINE_REBUILD
#$EXEFILE $CFGFILE $HORUS_CMDLINE_REMOTEEXEC > $LOGFILE
$EXEFILE $CFGFILE $HORUS_CMDLINE_REMOTEEXEC

cd $BINDIR

